### ISSUE TITLE
Coding keys

### ISSUE THREAD

**Issue by djmckee** [AidenForrest/my-first-blog#1]
https://github.com/AidenForrest/my-first-blog/blob/4b51ae1aba83cdc9e99018481d2a16ab9759c4c9/iOS%20App/Blog/Blog/Post.swift#L15

Hey @AidenForrest - could you look at using swift's coding keys to keep these in `camelCase` within the swift code please a a good practice?

https://stackoverflow.com/a/44396824

**Comment by AidenForrest** [comment]
Hello @djmckee

I've sorted that now and pushed my new code to main.

Thanks, Aiden
