### ISSUE TITLE
Loop types

### ISSUE THREAD

**Issue by djmckee** [AidenForrest/my-first-blog#2]
https://github.com/AidenForrest/my-first-blog/blob/4b51ae1aba83cdc9e99018481d2a16ab9759c4c9/iOS%20App/Blog/Blog/CommentViewController.swift#L35

Hey @AidenForrest - please could you have a look at moving these to the modern `for in` loop types: https://www.programiz.com/swift-programming/for-in-loop#for-in

**Comment by AidenForrest** [comment]
Hello @djmckee 

I've updated it. Would you be able to take a look at the code below as I need to keep track of the count in order to see which comment I should show when the segment is selected using the segment index.
`                        // Post for loop update
                        var count = 0
                        for post in posts {
                            if count == index {
                                DispatchQueue.main.async { [self] in
                                    author.text = post.author
                                    body.text = post.text
                                  }
                            }
                            count += 1
                        }
                    }`

Thanks, Aiden

**Comment by AidenForrest** [comment]
```swift
                      // Post for loop update
                        var count = 0
                        for post in posts {
                            if count == index {
                                DispatchQueue.main.async { [self] in
                                    author.text = post.author
                                    body.text = post.text
                                  }
                            }
                            count += 1
                        }
```

**Comment by AidenForrest** [comment]
Hello @djmckee 

I have updated the code however would you be able to confirm using a count to show the selected comment is good practice just as this was needed to match the comment with the index of the segment.

```swift
let index = segments.selectedSegmentIndex
// Post for loop update
var count = 0
for post in posts {
    if count == index {
        DispatchQueue.main.async { [self] in
        author.text = post.author
        body.text = post.text
        }
    }
    count += 1
}
```

Thanks, Aiden
